### ISSUE TITLE
出问题了，如何解决呀？

### ISSUE THREAD

**Issue by Lzu-yue** [kcqnly/VSCode-C51#1]
main.c
'"\C51.EXE"' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
UART.c
'"\C51.EXE"' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
'"\A51.EXE"' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
系统找不到指定的文件。
系统找不到指定的文件。
C:\Users\11467\Desktop\project\code\51\VSCode-C51-master\environment\C51S.LIB
'"\BL51.EXE"' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
'"\OH51.EXE"' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
Compiled successfully: output\main.hex

终端将被任务重用，按任意键关闭。

**Comment by FeliksLv01** [comment]
C51的路径修改对了吗，可以观看视频教程https://www.bilibili.com/video/BV1g7411B7vY/
